---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  annotations:
    fluxcd.io/automated: "true"
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 2
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: 322378525166.dkr.ecr.us-east-1.amazonaws.com/github-action:eks-tomcat-872fdaa4233828921758a9cb1caabcbc96cb647e
        name: nginx
        ports:
        - containerPort: 80
