---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: synerzip
  annotations:
    fluxcd.io/automated: true
spec:
  selector:
    matchLabels:
      run: nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: nginx
    spec:
      containers:
      - image: 322378525166.dkr.ecr.us-east-1.amazonaws.com/github-action:eks-nginx-ef052099ed5aa25559e74db79b15927e9f0be028
        name: nginx
