--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
spec: 
  selector: 
    matchLabels: 
      run: nginx
  replicas: 3
  template: 
    metadata: 
      labels: 
        run: nginx
    spec: 
      containers: 
      - 
        image: 322378525166.dkr.ecr.us-east-1.amazonaws.com/github-action:eks-tomcat-81a52a3af297266116c15f975798ec2fe8740380
        name: nginx
        ports: 
        - containerPort: 80
