--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
spec: 
  selector: 
    matchLabels: 
      run: nginx
  replicas: 2
  template: 
    metadata: 
      labels: 
        run: nginx
    spec: 
      containers: 
      - 
        image: "vivekbangare2492/ngnix:1"
        name: nginx
        ports: 
        - containerPort: 80