--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: nginx
spec: 
  selector: 
    matchLabels: 
      run: nginx
  replicas: 2
  template: 
    metadata: 
      labels: 
        run: nginx
    spec: 
      containers: 
      - 
        image: "322378525166.dkr.ecr.us-east-1.amazonaws.com/github-action:eks-tomcat-f8dbb252654fdcc3a2e03797d1168f3571869f94"
        name: nginx
        ports: 
        - containerPort: 80
