--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    run: nginx
  name: nginx
  namespace: synerzip
spec: 
  ports: 
  - port: 80
    protocol: TCP
  selector: 
    run: nginx
  type: LoadBalancer
