--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: tomcat
spec: 
  selector: 
    matchLabels: 
      run: tomcat
  replicas: 2
  template: 
    metadata: 
      labels: 
        run: tomcat
    spec: 
      containers: 
      - 
        name: tomcat
        image: 322378525166.dkr.ecr.us-east-1.amazonaws.com/github-action:eks_tomcat_a72bbe82859e3dbcb382837a9bc850d54e0820fc
        ports: 
        - containerPort: 8080
